#Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
var = int(input("Digite aqui um número para ver sua tabuada: "))
print("{} X {} = {}".format(var,1, var * 1))
print("{} X {} = {}".format(var,2, var * 2))
print("{} X {} = {}".format(var,3, var * 3))
print("{} X {} = {}".format(var,4, var * 4))
print("{} X {} = {}".format(var,5, var * 5))
print("{} X {} = {}".format(var,6, var * 6))
print("{} X {} = {}".format(var,7, var * 7))
print("{} X {} = {}".format(var,8, var * 8))
print("{} X {} = {}".format(var,9, var * 9))
print("{} X {} = {}".format(var,10, var * 10))
